# Generated by Django 2.0.8 on 2018-09-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20180903_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerscorecard',
            old_name='showcase_name',
            new_name='showcase',
        ),
    ]
