# Generated by Django 2.0 on 2019-01-08 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0008_document_file_size'),
        ('showcase', '0003_auto_20190102_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='webm_animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
