# Generated by Django 2.0 on 2019-01-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_station_webm_animation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the field layout name here', max_length=100)),
                ('value', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='group',
            field=models.CharField(choices=[('Shooting', 'Shooting'), ('Dribbling', 'Dribbling'), ('Passing', 'Passing'), ('Control', 'Control')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='station',
            name='scoring_criteria',
            field=models.ManyToManyField(help_text='Add as many scoring criteria as apply', related_name='stations', to='showcase.ScoringCriteria'),
        ),
    ]
