# Generated by Django 2.0 on 2019-01-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_auto_20190109_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringcriteria',
            options={'ordering': ('-value',)},
        ),
    ]
