# Generated by Django 2.0 on 2019-01-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_auto_20190112_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='stations',
            field=models.ManyToManyField(help_text='Stations associated to showcase.', related_name='showcase', to='showcase.Station'),
        ),
    ]
