# Generated by Django 2.0 on 2019-01-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_showcase_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcase',
            name='stations',
        ),
        migrations.AddField(
            model_name='station',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
