# Generated by Django 2.0 on 2019-01-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_auto_20190116_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('index',)},
        ),
    ]
