# Generated by Django 2.0 on 2019-01-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_auto_20190116_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='animation',
            field=models.FileField(blank=True, null=True, upload_to='stations'),
        ),
        migrations.AlterField(
            model_name='station',
            name='webm_animation',
            field=models.FileField(blank=True, null=True, upload_to='stations'),
        ),
    ]
