# Generated by Django 2.0 on 2019-01-19 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_auto_20190117_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='attempts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default='{}', help_text='Array of associated field names', size=None),
            preserve_default=False,
        ),
    ]
