# Generated by Django 2.0 on 2019-01-19 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_station_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='attempts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Array of associated field names', null=True, size=None),
        ),
    ]
