# Generated by Django 2.0 on 2019-01-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0016_auto_20190119_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='scorecard_name',
        ),
    ]
