# Generated by Django 2.0 on 2019-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0017_remove_station_scorecard_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscorecard',
            name='player_number',
        ),
        migrations.AddField(
            model_name='player',
            name='player_number',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
