# Generated by Django 2.0 on 2019-01-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_auto_20190120_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='grass_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showcase',
            name='rain',
            field=models.BooleanField(default=False),
        ),
    ]
