# Generated by Django 2.0 on 2019-01-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0019_auto_20190121_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcase',
            name='field_condition',
        ),
        migrations.RemoveField(
            model_name='showcase',
            name='weather',
        ),
    ]
