# Generated by Django 2.0 on 2019-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0020_auto_20190121_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscorecard',
            name='cross_l_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Cross Left 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='cross_l_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Cross Left 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='cross_r_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Cross Right 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='cross_r_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Cross Right 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='finisher_l_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Finish Left Foot 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='finisher_l_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Finish Left Foot 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='finisher_l_3',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Finish Left Foot 3'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='finisher_r_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Finish Right Foot 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='finisher_r_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Finish Right Foot 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='finisher_r_3',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Finish Right Foot 3'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='long_l_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Long Pass Left Foot 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='long_l_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Long Pass Left Foot 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='long_r_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Long Pass Right Foot 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='long_r_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Long Pass Right Foot 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='shoot_pk',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 10.0', verbose_name='Penalty Kick'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='shoot_run_l_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Shot Left Foot 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='shoot_run_l_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Shot Left Foot 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='shoot_run_l_3',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Shot Left Foot 3'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='shoot_run_r_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Shot Right Foot 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='shoot_run_r_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Shot Right Foot 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='shoot_run_r_3',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 7.5', verbose_name='Shot Right Foot 3'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='side_pass_l_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Side Pass Left 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='side_pass_l_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Side Pass Left 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='side_pass_l_3',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Side Pass Left 3'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='side_pass_r_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Side Pass Right 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='side_pass_r_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Side Pass Right 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='side_pass_r_3',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Side Pass Right 3'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='throw_between_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 2.5', verbose_name='Throw-in between far cones 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='throw_between_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 2.5', verbose_name='Throw-in between far cones 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='throw_inside_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 2.5', verbose_name='Throw Inside Box 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='throw_inside_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 2.5', verbose_name='Throw Inside Box 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='weigh_pass_l_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Weighted Pass Left 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='weigh_pass_l_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Weighted Pass Left 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='weigh_pass_l_3',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Weighted Pass Left 3'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='weigh_pass_r_1',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Weighted Pass Right 1'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='weigh_pass_r_2',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Weighted Pass Right 2'),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='weigh_pass_r_3',
            field=models.FloatField(choices=[(1.0, '5 Star'), (0, '1 Star')], default=0.0, help_text='Select an option. Weight: 4.5', verbose_name='Weighted Pass Right 3'),
        ),
    ]
