# Generated by Django 2.0 on 2019-02-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190203_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='header_description',
        ),
    ]
