# Generated by Django 2.0 on 2019-02-03 23:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('video', wagtail.embeds.blocks.EmbedBlock()), ('image_1', wagtail.images.blocks.ImageChooserBlock()), ('image_2', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_3', wagtail.images.blocks.ImageChooserBlock(required=False))], blank=True, null=True),
        ),
    ]
