# Generated by Django 2.0 on 2019-02-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190204_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
